"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
	# Plugins
	{ on = "M",         run = "plugin mount" },
	{ on = ["<C-p>", "d"],     run = "plugin diff" },
	{ on = ["g", "j"],  run = "plugin first-non-directory", desc = "Jumps to the first file" },
	{ on = "z",         run = "plugin zoxide" },
	{ on = "Z",         run = "plugin fzf" },
]
