# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio          = [ 1, 3, 3 ]
linemode       = "size"

[opener]
zathura = [
	{ run = 'zathura "$@"', orphan = true, for = "unix", desc = "Open with Zathura" },
]
extract-folder = [
	{ run = 'filename="${1%.*}"; mkdir -p "$filename"; unar -o "$filename" "$1"', desc = "Extract to folder", for = "unix" },
]

[open]
prepend_rules = [
	{ name = "*.pdf", use = ["zathura", "reveal"] },
	{ mime = "application/*zip", use = [ "extract", "extract-folder", "reveal" ] },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", use = [ "extract", "extract-folder", "reveal" ] },
]
