#!/usr/bin/env bash

test -z "$joshuto_wrap_id" && exit 1;

file="$1"       # Full path of the previewed file
x="$2"          # x coordinate of upper left cell of preview area
y="$3"          # y coordinate of upper left cell of preview area
width="$4"      # Width of the preview pane (number of fitting characters)
height="$5"     # Height of the preview pane (number of fitting characters)

# Determine the mimetype of the file
mimetype=$(file --mime-type -Lb "$file")

filename=$(basename $(echo "$file" | tr ' ' '_'))

case "$mimetype" in
    image/png | image/jpeg)
        # Display the image if it's a PNG or JPEG
        show_image "$file" $x $y $width $height
        ;;
    application/pdf)
        # Check if the PNG conversion does not exist
        if [[ ! -f "/tmp/$filename.png" ]]; then
            # Convert the first page of the PDF to a PNG image
            pdftoppm -f 1 -l 1 "$file" > "/tmp/$filename.png"
        fi
        # Display the converted PNG image
        show_image "/tmp/$filename.png" $x $y $width $height
        ;;
    *)
        # If the file is not an image or PDF, remove the image preview
        remove_image
        ;;
esac