# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio         = [ 1, 3, 3 ]
linemode      = "size"
sort_by       = "natural"

[preview]
wrap       = "yes"
max_width  = 2500
max_height = 1500

[input]
cursor_blink = true

[opener]
zathura = [
	{ run = 'zathura "$@"', orphan = true, for = "unix", desc = "Open with Zathura" },
]
qimgv = [
	{ run = 'qimgv "$@"', orphan = true, for = "unix", desc = "Open with qimgv" },
]
libreoffice = [
	{ run = 'libreoffice "$@"', orphan = true, for = "unix", desc = "Open with libreoffice" },
]
subtitle = [
	{ run = ''' echo sub-add "'$0'" | socat - /tmp/mpv.sock ''', desc = "Add sub to MPV" },
]
play = [
	{ run = 'mpv --force-window --input-ipc-server=/tmp/mpv.sock "$@"', orphan = true, for = "unix" },
]

[open]
prepend_rules = [
	{ name = "*.pdf", use = ["zathura", "reveal"] },
	{ name = "*.{xls,xlsx,xlsm,xltx,xlsb,odt,ods,odp,doc,docx,ppt,pptx}", use = ["libreoffice", "reveal"] },
  { mime = "image/*", use = [ "qimgv", "open", "reveal" ] },
  { name = "*.{ass,srt,ssa,sty,sup,vtt}", use = [ "subtitle", "edit" ] },
]

[plugin]
prepend_fetchers = [
	{ id = "git", name = "*", run = "git" },
	{ id = "git", name = "*/", run = "git" },
]
