#!usr/bin/env bash

wallpaper_path=~/Pictures/wallpapers
img="$(ls $wallpaper_path | shuf -n 1)"

pgrep -x sxhkd > /dev/null || sxhkd -m -1 &

xsetroot -cursor_name left_ptr &
xset r rate 350 20 &

"$HOME/.config/eww/scripts/start.sh" &
"$HOME/bin/launch.sh" &
picom &
feh --bg-scale "$wallpaper_path/$img" &
ibus-daemon -drxR &
nm-applet &
pgrep -x battery-alert >/dev/null || ~/bin/battery-alert &
pidof syncthing || syncthing -no-browser &
trash-empty -f 40 &
# wmname LG3D & # This is for IntellJ and IntellJ-based (Android Studio)
copyq &

bspc wm -O eDP-1 HDMI-1
bspc monitor eDP-1 -d 1 2 3 4 5 6 7
bspc monitor HDMI-1 -d 8 9 10

bspc config border_width 2
bspc config window_gap 12

bspc config focused_border_color \#ad8ee6

bspc config split_ratio 0.55
bspc config borderless_monocle true
bspc config gapless_monocle true

# bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

"$HOME/bin/set_bspwm_rule" &
